# Identitas project — sesuaikan dengan yang ada di SonarCloud
sonar.projectKey=timsurrealedu_SonarCloudTrivy
sonar.organization=timsurrealedu

# Nama project
sonar.projectName=BNCC RnD DevSecOps Demo
sonar.projectVersion=1.0

# Source code dan test
sonar.sources=src
sonar.tests=tests

# Coverage report dari Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# File yang tidak perlu di-scan
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/coverage/**

sonar.sourceEncoding=UTF-8
